version: '3.8'

services:
  front:
    build:
      context: ./front
    container_name: front
    ports:
      - "8080:8080"
    networks:
      - network
  back:
    build:
      context: ./back
    container_name: back
    environment:
      - FLASK_APP=main.py
      - FLASK_ENV=development
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - network
  db:
    image: keinos/sqlite3:latest
    container_name: db-container
    volumes:
      - db-data:/data
    networks:
      - network
    command: ["sleep", "infinity"]

networks:
  network:
    driver: bridge

volumes:
  db-data: